### ISSUE TITLE
点击下载完成项后程序崩溃

### ISSUE THREAD

**Issue by Kanadeforever** [DanteAndroid/91Pop#1]
点击完成项程序崩溃，无法调用播放器

**Comment by DanteAndroid** [comment]
有log提供一下吗~因为要翻墙，测bug比较麻烦

**Comment by Kanadeforever** [comment]
抱歉，不熟悉这块，在哪看的到log？

**Comment by DanteAndroid** [comment]
已经修复。请[更新](https://github.com/DanteAndroid/91Pop/releases/tag/v1.0.1)
